version: Wh3"

networks:
  monitoring:

volumes:
  influxdb: {}
  grafana: {}


services:
  influxdb:
    image: influxdb:2.5.1
    ports:
      - 8086:8086
    networks:
      - monitoring
    volumes:
      - influxdb:/var/lib/influxdb2
      - influxdb:/etc/influxdb2
    
  grafana:
    image: grafana/grafana:8.4.5
    ports:
      - 3000:3000
    networks:
      - monitoring
    volumes:
      - grafana:/var/lib/grafana

