version: "3.8"

networks:
  monitoring:

services:
  influxdb:
    image: influxdb:2.5.1
    hostname: influxdb
    ports:
      - ${INFLUXDB_PORT}:8086
    networks:
      - monitoring
    volumes:
      - influxdb_vol:/var/lib/influxdb2
      - influxdb_vol:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}

  postgres:
    image: postgres
    restart: always
    hostname: postgres
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - monitoring
    volumes:
      - postgres_vol:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - ${PGADMIN_PORT}:80
    networks:
      - monitoring
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}  
    depends_on:
      - postgres
  
  postgrest:
    image: postgrest/postgrest
    ports:
      - ${POSTGREST_PORT}:3000
    networks:
      - monitoring
    environment:
      - PGRST_DB_URI=postgres://authenticator:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_USER}
      - PGRST_OPENAPI_SERVER_PROXY_URI=http://127.0.0.1:3001
      - PGRST_JWT_SECRET=${POSTGREST_JWT}
      - PGRST_JWT_SECRET_IS_BASE64=false
    depends_on:
      - postgres

  grafana:
    image: grafana/grafana:8.4.5
    hostname: grafana
    ports:
      - ${GRAFANA_PORT}:3000
    networks:
      - monitoring
    volumes:
      - grafana_vol:/var/lib/grafana
    env_file:
      - .env
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}

volumes:
  influxdb_vol:
  postgres_vol:
  grafana_vol:

